CREATE TABLE IF NOT EXISTS "film" (
    "film_id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
    "description" varchar(200) NOT NULL,
    "release" date NOT NULL,
    "duration" integer NOT NULL,
    "rating_id" varchar NOT NULL,
    CONSTRAINT "pk_film" PRIMARY KEY (
        "film_id"
     )
);

CREATE TABLE IF NOT EXISTS "user" (
    "user_id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "email_address" varchar NOT NULL,
    "login" varchar NOT NULL,
    "name" varchar NOT NULL,
    "birthday" date NOT NULL,
    CONSTRAINT "pk_user" PRIMARY KEY (
        "user_id"
     ),
    CONSTRAINT "uc_user_email_address" UNIQUE (
        "email_address"
    )
);

CREATE TABLE IF NOT EXISTS "rating" (
    "rating_id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
	CONSTRAINT "pk_rating" PRIMARY KEY (
        "rating_id"
     )
);

CREATE TABLE IF NOT EXISTS "genre" (
    "genre_id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
    CONSTRAINT "pk_genre" PRIMARY KEY (
        "genre_id"
     )
);

CREATE TABLE IF NOT EXISTS "film_genre" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "film_id" bigint NOT NULL,
    "genre_id" integer NOT NULL,
    CONSTRAINT "pk_film_genre" PRIMARY KEY (
        "id"
     )
);

CREATE TABLE IF NOT EXISTS "user_friend" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "friend_id" bigint NOT NULL,
    CONSTRAINT "pk_user_friend" PRIMARY KEY (
        "id"
     )
);

CREATE TABLE IF NOT EXISTS "film_like" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "film_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    CONSTRAINT "pk_film_like" PRIMARY KEY (
        "id"
     )
);

ALTER TABLE "film" ADD CONSTRAINT IF NOT EXISTS "fk_film_rating_id" FOREIGN KEY("rating_id") 
REFERENCES "rating" ("rating_id");

ALTER TABLE "film_genre" ADD CONSTRAINT IF NOT EXISTS "fk_film_genre_film_id" FOREIGN KEY("film_id")
REFERENCES "film" ("film_id");

ALTER TABLE "film_genre" ADD CONSTRAINT IF NOT EXISTS "fk_film_genre_genre_id" FOREIGN KEY("genre_id")
REFERENCES "genre" ("genre_id");

ALTER TABLE "user_friend" ADD CONSTRAINT IF NOT EXISTS "fk_user_friend_user_id" FOREIGN KEY("user_id")
REFERENCES "user" ("user_id");

ALTER TABLE "user_friend" ADD CONSTRAINT IF NOT EXISTS "fk_user_friend_friend_id" FOREIGN KEY("friend_id")
REFERENCES "user" ("user_id");

ALTER TABLE "film_like" ADD CONSTRAINT IF NOT EXISTS "fk_film_like_film_id" FOREIGN KEY("film_id")
REFERENCES "film" ("film_id");

ALTER TABLE "film_like" ADD CONSTRAINT IF NOT EXISTS "fk_film_like_user_id" FOREIGN KEY("user_id")
REFERENCES "user" ("user_id");